// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vitalify.Infrastructure.Persistence.Transaccional;

#nullable disable

namespace Vitalify.Infrastructure.Persistence.Transaccional.Migrations
{
    [DbContext(typeof(TransaccionalDbContext))]
    [Migration("20260929232414_Fase1_UsuariosYSesiones")]
    partial class Fase1_UsuariosYSesiones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("vitalify")
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vitalify.Domain.Auditoria.RegistroAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("accion");

                    b.Property<string>("Detalle")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("detalle");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_auditoria");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("ix_auditoria_fecha");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_auditoria_usuario_id");

                    b.ToTable("auditoria", "vitalify");
                });

            modelBuilder.Entity("Vitalify.Domain.Sesiones.SesionRefresco", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<string>("HashToken")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("hash_token")
                        .IsFixedLength();

                    b.Property<Guid?>("ReemplazadaPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("reemplazada_por_id");

                    b.Property<DateTime?>("RevocadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revocada_en");

                    b.Property<DateTime>("UltimoUsoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_uso_en");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_sesion_refresco");

                    b.HasIndex("HashToken")
                        .IsUnique()
                        .HasDatabaseName("ix_sesion_refresco_hash_token");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_sesion_refresco_usuario_id");

                    b.ToTable("sesion_refresco", "vitalify");
                });

            modelBuilder.Entity("Vitalify.Domain.Sesiones.TokenRevocado", b =>
                {
                    b.Property<string>("Jti")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("jti");

                    b.Property<DateTime>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Jti")
                        .HasName("pk_token_revocado");

                    b.HasIndex("ExpiraEn")
                        .HasDatabaseName("ix_token_revocado_expira_en");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_token_revocado_usuario_id");

                    b.ToTable("token_revocado", "vitalify");
                });

            modelBuilder.Entity("Vitalify.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("correo");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("HashContrasena")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("hash_contrasena");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rol");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("ux_usuario_correo");

                    b.HasIndex("Rol")
                        .HasDatabaseName("ix_usuario_rol");

                    b.ToTable("usuario", "vitalify");
                });

            modelBuilder.Entity("Vitalify.Domain.Auditoria.RegistroAuditoria", b =>
                {
                    b.HasOne("Vitalify.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_auditoria_usuario_usuario_id");
                });

            modelBuilder.Entity("Vitalify.Domain.Sesiones.SesionRefresco", b =>
                {
                    b.HasOne("Vitalify.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sesion_refresco_usuario_usuario_id");
                });

            modelBuilder.Entity("Vitalify.Domain.Sesiones.TokenRevocado", b =>
                {
                    b.HasOne("Vitalify.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_token_revocado_usuario_usuario_id");
                });
#pragma warning restore 612, 618
        }
    }
}
