// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vitalify.Infrastructure.Persistence.Historial;

#nullable disable

namespace Vitalify.Infrastructure.Persistence.Historial.Migrations
{
    [DbContext(typeof(HistorialDbContext))]
    partial class HistorialDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("vitalify_historial")
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vitalify.Domain.Telemetria.EstadoSignosActual", b =>
                {
                    b.Property<Guid>("HospitalizacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("hospitalizacion_id");

                    b.Property<int?>("Bateria")
                        .HasColumnType("integer")
                        .HasColumnName("bateria");

                    b.Property<string>("CodigoDispositivo")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("codigo_dispositivo");

                    b.Property<DateTime?>("FcMedidoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fc_medido_en");

                    b.Property<int?>("FcValor")
                        .HasColumnType("integer")
                        .HasColumnName("fc_valor");

                    b.Property<DateTime?>("FrMedidoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fr_medido_en");

                    b.Property<int?>("FrValor")
                        .HasColumnType("integer")
                        .HasColumnName("fr_valor");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<DateTime?>("PadMedidoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pad_medido_en");

                    b.Property<int?>("PadValor")
                        .HasColumnType("integer")
                        .HasColumnName("pad_valor");

                    b.Property<DateTime?>("PasMedidoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pas_medido_en");

                    b.Property<int?>("PasValor")
                        .HasColumnType("integer")
                        .HasColumnName("pas_valor");

                    b.Property<DateTime?>("Spo2MedidoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("spo2_medido_en");

                    b.Property<int?>("Spo2Valor")
                        .HasColumnType("integer")
                        .HasColumnName("spo2_valor");

                    b.Property<DateTime?>("TempMedidoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("temp_medido_en");

                    b.Property<decimal?>("TempValor")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("temp_valor");

                    b.Property<DateTime?>("UltimaCaidaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_caida_en");

                    b.Property<DateTime?>("UltimaLecturaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_lectura_en");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("HospitalizacionId")
                        .HasName("pk_estado_signos_actual");

                    b.ToTable("estado_signos_actual", "vitalify_historial");
                });

            modelBuilder.Entity("Vitalify.Domain.Telemetria.IncidenciaTelemetria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoDispositivo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("codigo_dispositivo");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("detalle");

                    b.Property<Guid?>("HospitalizacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("hospitalizacion_id");

                    b.Property<DateTime>("OcurridaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocurrida_en");

                    b.Property<bool>("RequiereNuevaLectura")
                        .HasColumnType("boolean")
                        .HasColumnName("requiere_nueva_lectura");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<decimal?>("ValorRecibido")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("valor_recibido");

                    b.Property<string>("Variable")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("variable");

                    b.HasKey("Id")
                        .HasName("pk_incidencia_telemetria");

                    b.HasIndex("OcurridaEn")
                        .IsDescending()
                        .HasDatabaseName("ix_incidencia_telemetria_ocurrida_en");

                    b.ToTable("incidencia_telemetria", "vitalify_historial");
                });

            modelBuilder.Entity("Vitalify.Domain.Telemetria.LecturaSignos", b =>
                {
                    b.Property<string>("CodigoDispositivo")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("codigo_dispositivo");

                    b.Property<DateTime>("MedidoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("medido_en");

                    b.Property<int?>("Bateria")
                        .HasColumnType("integer")
                        .HasColumnName("bateria");

                    b.Property<bool>("Caida")
                        .HasColumnType("boolean")
                        .HasColumnName("caida");

                    b.Property<int?>("Fc")
                        .HasColumnType("integer")
                        .HasColumnName("fc");

                    b.Property<int?>("Fr")
                        .HasColumnType("integer")
                        .HasColumnName("fr");

                    b.Property<Guid>("HospitalizacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("hospitalizacion_id");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origen");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<int?>("Pad")
                        .HasColumnType("integer")
                        .HasColumnName("pad");

                    b.Property<int?>("Pas")
                        .HasColumnType("integer")
                        .HasColumnName("pas");

                    b.Property<DateTime>("RecibidoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recibido_en");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    b.Property<int?>("Spo2")
                        .HasColumnType("integer")
                        .HasColumnName("spo2");

                    b.Property<decimal?>("Temperatura")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("temperatura");

                    b.HasKey("CodigoDispositivo", "MedidoEn")
                        .HasName("pk_lectura_signos");

                    b.HasIndex("HospitalizacionId", "MedidoEn")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_lectura_signos_hospitalizacion_id_medido_en");

                    b.ToTable("lectura_signos", "vitalify_historial");
                });
#pragma warning restore 612, 618
        }
    }
}
